version: 2
project_name: hexatiles

before:
  hooks:
    - go mod tidy

builds:
  - id: hexatiles
    main: ./cmd/hexatiles
    env: [CGO_ENABLED=1]     # CGO ON
    flags: [ -trimpath ]
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos: [darwin, linux]    # no windows yet
    goarch: [amd64, arm64]   # darwin/arm64 works; linux/arm64 is ignored by the linux job below
    # NOTE: we'll filter OS per job in the workflow

archives:
  - id: default
    formats: [tar.gz, zip]
    # zip will be used only if goos == windows (not in v0.1)
    format_overrides:
      - goos: darwin
        format: tar.gz
      - goos: linux
        format: tar.gz
    files:
      - LICENSE
      - README.md
      - examples/demo/index.html

checksum:
  name_template: "checksums.txt"

changelog:
  use: git
  sort: asc
  filters:
    exclude: ["^docs:", "^test:", "^chore:"]

brews:
  - name: hexatiles
    repository:
      owner: samfargo
      name: homebrew-tap
      branch: main
    directory: Formula
    homepage: https://github.com/samfargo/HexaTiles
    description: Parquet → H3 polygons → PMTiles in one command
    license: Apache-2.0
    test: |
      system "#{bin}/hexatiles", "--help"

# remove scoops for now: no Windows binary yet