version: 2
project_name: hexatiles

release:
  mode: append

before:
  hooks:
    - go mod tidy

builds:
  - id: hexatiles-linux-amd64
    main: ./cmd/hexatiles
    env: [CGO_ENABLED=1]
    flags: [ -trimpath ]
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos: [linux]
    goarch: [amd64]
    binary: hexatiles

archives:
  - id: linux
    builds: [hexatiles-linux-amd64]
    formats: [tar.gz]
    files:
      - LICENSE
      - README.md
      - examples/demo/index.html

checksum:
  disable: true

changelog:
  use: git
  sort: asc