version: 2
project_name: hexatiles

release:
  mode: append

before:
  hooks:
    - go mod tidy

builds:
  - id: hexatiles-darwin-amd64
    main: ./cmd/hexatiles
    env: [CGO_ENABLED=1]
    flags: [ -trimpath ]
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos: [darwin]
    goarch: [amd64]
    binary: hexatiles

archives:
  - id: darwin-amd64
    builds: [hexatiles-darwin-amd64]
    formats: [tar.gz]
    files:
      - LICENSE
      - README.md
      - examples/demo/index.html

checksum:
  name_template: "checksums.txt"

changelog:
  use: git
  sort: asc

brews:
  - name: hexatiles
    repository:
      owner: samfargo
      name: homebrew-tap
      branch: main
    directory: Formula
    homepage: https://github.com/samfargo/HexaTiles
    description: Parquet → H3 polygons → PMTiles in one command
    license: Apache-2.0
    test: |
      system "#{bin}/hexatiles", "--help"