name: release
on:
  repository_dispatch:
    types: [release-please]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  darwin_arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-go@v5
        with: { go-version: '1.22' }
      - name: Install libh3
        run: brew install h3
      - name: GoReleaser (darwin/arm64)
        uses: goreleaser/goreleaser-action@v6
        with:
          version: v2
          args: release --clean --config .goreleaser.darwin-arm64.yaml --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ github.event.client_payload.tag_name }}

  linux_amd64:
    runs-on: ubuntu-latest
    needs: darwin_arm64
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-go@v5
        with: { go-version: '1.22' }

      - name: Install libh3
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make gcc g++ git
          git clone --depth 1 https://github.com/uber/h3.git
          cd h3
          cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release .
          make -j"$(nproc)"
          sudo make install
          sudo ldconfig

      - name: GoReleaser (linux/amd64)
        uses: goreleaser/goreleaser-action@v6
        with:
          version: v2
          args: release --clean --config .goreleaser.linux-amd64.yaml --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ github.event.client_payload.tag_name }}

  darwin_amd64:
    runs-on: macos-13
    needs: darwin_arm64
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-go@v5
        with: { go-version: '1.22' }
      - name: Install libh3
        run: brew install h3
      - name: GoReleaser (darwin/amd64)
        uses: goreleaser/goreleaser-action@v6
        with:
          version: v2
          args: release --clean --config .goreleaser.darwin-amd64.yaml --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ github.event.client_payload.tag_name }}