name: release
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write   # create/update the GitHub Release in this repo

jobs:
  release-linux:
    name: GoReleaser (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-go@v5
        with: { go-version: '1.22' }
      - name: Install libh3 (C library)
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make gcc g++ git
          git clone --depth 1 https://github.com/uber/h3.git
          cd h3
          cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release .
          make -j"$(nproc)"
          sudo make install
          sudo ldconfig
      - name: GoReleaser (linux)
        uses: goreleaser/goreleaser-action@v6
        with:
          version: v2
          args: release --clean --config .goreleaser.linux.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}

  release-macos:
    name: GoReleaser (macOS)
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-go@v5
        with: { go-version: '1.22' }
      - name: Install libh3
        run: brew install h3
      - name: GoReleaser (darwin + brew/scoop)
        uses: goreleaser/goreleaser-action@v6
        with:
          version: v2
          args: release --clean --config .goreleaser.darwin.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}